import { useState } from "react";

/* Wilson score confidence interval for a proportion (95%) */
function wilsonCI(pctVal, n) {
  if (!n || n === 0) return "";
  const z = 1.96;
  const p = pctVal / 100;
  const d = 1 + (z * z) / n;
  const c = (p + (z * z) / (2 * n)) / d;
  const s = z * Math.sqrt((p * (1 - p) + (z * z) / (4 * n)) / n) / d;
  const lo = Math.max(0, c - s) * 100;
  const hi = Math.min(1, c + s) * 100;
  return `[${lo.toFixed(1)}–${hi.toFixed(1)}%]`;
}

/* ──────────────────────────────────────────────────────────────────
   All numbers sourced directly from outputs/population/dashboard_data.json
   Generated by scripts/run_population.py on 1,473,595 scored fills
   across 67,085 unique patients (CMS DE-SynPUF 2008-2010).
   ────────────────────────────────────────────────────────────────── */

const DATA = {
  overview: {
    total_fills: 1_473_595,
    total_patients: 67_085,
    total_unique_drugs: 1_271,
    pct_late: 76.2,
    mean_risk_score: 0.525,
    tier_counts: { HIGH: 809_536, MODERATE: 397_695, LOW: 266_364 },
    tier_pct: { HIGH: 54.9, MODERATE: 27.0, LOW: 18.1 },
    tier_actual_late: { LOW: 46.3, MODERATE: 71.6, HIGH: 88.2 },
  },
  high_risk: { count: 47_272, pct_of_total: 70.5, mean_fills: 23.4, mean_drugs: 11.2, mean_late_pct: 80.2 },
  by_quarter: [
    { label: "2008 Q1", pct_late: 82.5, pct_high: 76.6, n_fills: 148_750 },
    { label: "2008 Q2", pct_late: 81.8, pct_high: 66.4, n_fills: 200_894 },
    { label: "2008 Q3", pct_late: 80.9, pct_high: 61.4, n_fills: 194_828 },
    { label: "2008 Q4", pct_late: 80.0, pct_high: 58.4, n_fills: 183_296 },
    { label: "2009 Q1", pct_late: 78.4, pct_high: 54.4, n_fills: 165_787 },
    { label: "2009 Q2", pct_late: 76.2, pct_high: 50.1, n_fills: 152_019 },
    { label: "2009 Q3", pct_late: 73.8, pct_high: 45.7, n_fills: 135_362 },
    { label: "2009 Q4", pct_late: 70.3, pct_high: 41.3, n_fills: 112_501 },
    { label: "2010 Q1", pct_late: 65.8, pct_high: 37.3, n_fills: 85_202 },
    { label: "2010 Q2", pct_late: 59.3, pct_high: 32.6, n_fills: 57_192 },
    { label: "2010 Q3", pct_late: 48.3, pct_high: 28.7, n_fills: 29_496 },
    { label: "2010 Q4", pct_late: 24.4, pct_high: 24.7, n_fills: 8_268 },
  ],
  by_drug_class: [
    { name: "ARBs", n_fills: 85_042, pct_late: 88.4, pct_high: 81.6, n_patients: 35_267 },
    { name: "Statins (HMG CoA)", n_fills: 73_074, pct_late: 88.6, pct_high: 81.8, n_patients: 32_863 },
    { name: "Fibrates", n_fills: 32_076, pct_late: 88.0, pct_high: 80.4, n_patients: 19_598 },
    { name: "Platelet inhibitors", n_fills: 6_939, pct_late: 90.4, pct_high: 85.9, n_patients: 5_808 },
    { name: "Aminosalicylates", n_fills: 4_618, pct_late: 89.6, pct_high: 83.8, n_patients: 3_854 },
    { name: "Bile acid sequestrants", n_fills: 3_154, pct_late: 91.3, pct_high: 84.5, n_patients: 2_784 },
    { name: "Thyroid hormones", n_fills: 1_337, pct_late: 89.9, pct_high: 84.2, n_patients: 1_209 },
  ],
  by_drug: [
    { name: "Pravastatin 40mg", n_fills: 5_067, pct_late: 89.8 },
    { name: "Atacand (candesartan)", n_fills: 9_535, pct_late: 89.6 },
    { name: "Sulfasalazine 500mg", n_fills: 4_618, pct_late: 89.6 },
    { name: "Diovan (valsartan)", n_fills: 15_192, pct_late: 89.4 },
    { name: "Lovastatin 10mg", n_fills: 21_761, pct_late: 88.4 },
    { name: "Avapro (irbesartan)", n_fills: 25_161, pct_late: 88.3 },
    { name: "Simvastatin 20mg", n_fills: 17_192, pct_late: 88.1 },
    { name: "Lipitor (atorvastatin)", n_fills: 14_147, pct_late: 88.1 },
    { name: "Gemfibrozil 600mg", n_fills: 30_035, pct_late: 88.0 },
    { name: "Cozaar (losartan)", n_fills: 22_119, pct_late: 87.0 },
  ],
  by_age: [
    { group: "<55", n_patients: 6_931, n_fills: 164_040, pct_late: 76.0, pct_high: 55.2 },
    { group: "55-64", n_patients: 5_823, n_fills: 123_957, pct_late: 76.0, pct_high: 55.1 },
    { group: "65-74", n_patients: 26_884, n_fills: 502_648, pct_late: 76.7, pct_high: 55.5 },
    { group: "75-84", n_patients: 23_284, n_fills: 438_378, pct_late: 76.0, pct_high: 54.7 },
    { group: "85+", n_patients: 12_023, n_fills: 244_572, pct_late: 75.5, pct_high: 54.0 },
  ],
  by_sex: [
    { label: "Female", n_patients: 39_826, n_fills: 908_309, pct_late: 76.1, pct_high: 54.9 },
    { label: "Male", n_patients: 27_259, n_fills: 565_286, pct_late: 76.3, pct_high: 54.9 },
  ],
  by_race: [
    { label: "White", n_patients: 54_985, n_fills: 1_199_776, pct_late: 76.2, pct_high: 55.0 },
    { label: "Black", n_patients: 7_189, n_fills: 159_752, pct_late: 76.3, pct_high: 55.0 },
    { label: "Other", n_patients: 2_953, n_fills: 66_435, pct_late: 75.8, pct_high: 54.3 },
    { label: "Hispanic", n_patients: 1_958, n_fills: 47_632, pct_late: 75.9, pct_high: 54.6 },
  ],
  by_chronic: [
    { n: 0, pct_late: 77.2, pct_high: 55.8, n_patients: 28_158 },
    { n: 1, pct_late: 75.7, pct_high: 53.6, n_patients: 17_291 },
    { n: 2, pct_late: 76.0, pct_high: 54.4, n_patients: 16_827 },
    { n: 3, pct_late: 75.7, pct_high: 54.3, n_patients: 16_148 },
    { n: 4, pct_late: 75.8, pct_high: 54.6, n_patients: 14_645 },
    { n: 5, pct_late: 75.6, pct_high: 54.4, n_patients: 12_361 },
    { n: 6, pct_late: 75.8, pct_high: 54.9, n_patients: 9_439 },
    { n: 7, pct_late: 75.9, pct_high: 55.4, n_patients: 6_613 },
    { n: 8, pct_late: 76.5, pct_high: 56.5, n_patients: 3_741 },
    { n: 9, pct_late: 76.4, pct_high: 56.5, n_patients: 1_652 },
    { n: 10, pct_late: 77.4, pct_high: 59.2, n_patients: 453 },
    { n: 11, pct_late: 80.1, pct_high: 58.3, n_patients: 62 },
  ],
};

function StatCard({ icon, value, label, color, sub }) {
  return (
    <div className="an-stat">
      <span className="material-symbols-outlined" style={{ fontSize: 28, color, background: `${color}14`, borderRadius: 10, width: 44, height: 44, display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 }}>{icon}</span>
      <div>
        <div style={{ fontSize: 22, fontWeight: 800, fontFamily: "'Nunito',sans-serif", color: "var(--navy)", lineHeight: 1.1 }}>{value}</div>
        <div style={{ fontSize: 12, color: "#6b7280", fontWeight: 500, marginTop: 2 }}>{label}</div>
        {sub && <div style={{ fontSize: 11, color: "#9ca3af", marginTop: 1 }}>{sub}</div>}
      </div>
    </div>
  );
}

function HBar({ label, value, pct, maxPct = 100, color = "var(--accent)", sub, ci }) {
  const w = Math.max(2, (pct / maxPct) * 100);
  return (
    <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 8 }}>
      <div style={{ width: 140, textAlign: "right", fontSize: 13, fontWeight: 500, color: "#374151", flexShrink: 0 }}>{label}</div>
      <div style={{ flex: 1, height: 22, background: "#f3f4f6", borderRadius: 4, overflow: "hidden" }}>
        <div style={{ width: `${w}%`, height: "100%", background: color, borderRadius: 4, display: "flex", alignItems: "center", justifyContent: "flex-end", paddingRight: 6, fontSize: 10, fontWeight: 700, color: "#fff", minWidth: 28, transition: "width 600ms ease-out" }}>{value}</div>
      </div>
      {ci && <div style={{ fontSize: 10, color: "#9ca3af", width: 90, flexShrink: 0, fontFamily: "'JetBrains Mono',monospace" }}>{ci}</div>}
      {sub && !ci && <div style={{ fontSize: 11, color: "#9ca3af", width: 70, flexShrink: 0 }}>{sub}</div>}
    </div>
  );
}

function SectionCard({ icon, title, sub, children }) {
  return (
    <div className="an-section">
      <div className="an-section-hdr">
        <span className="material-symbols-outlined" style={{ fontSize: 22, color: "var(--accent)" }}>{icon}</span>
        <div>
          <div style={{ fontSize: 16, fontWeight: 700, color: "var(--navy)" }}>{title}</div>
          {sub && <div style={{ fontSize: 12, color: "#6b7280" }}>{sub}</div>}
        </div>
      </div>
      <div className="an-section-body">{children}</div>
    </div>
  );
}

function TierBar({ tier, count, pct, actualLate, color }) {
  return (
    <div style={{ display: "flex", alignItems: "center", gap: 12, padding: "10px 0", borderBottom: "1px solid #f3f4f6" }}>
      <span style={{ fontFamily: "'JetBrains Mono',monospace", fontSize: 12, fontWeight: 700, color, background: `${color}14`, padding: "3px 10px", borderRadius: 4, width: 80, textAlign: "center" }}>{tier}</span>
      <div style={{ flex: 1 }}>
        <div style={{ height: 14, background: "#f3f4f6", borderRadius: 3, overflow: "hidden" }}>
          <div style={{ width: `${pct}%`, height: "100%", background: color, borderRadius: 3, transition: "width 600ms" }} />
        </div>
      </div>
      <div style={{ textAlign: "right", minWidth: 100 }}>
        <div style={{ fontSize: 14, fontWeight: 700, color: "var(--navy)" }}>{count.toLocaleString()}</div>
        <div style={{ fontSize: 11, color: "#9ca3af" }}>{pct}% of fills</div>
      </div>
      <div style={{ textAlign: "right", minWidth: 80 }}>
        <div style={{ fontSize: 14, fontWeight: 700, color }}>{actualLate}%</div>
        <div style={{ fontSize: 11, color: "#9ca3af" }}>actual late</div>
      </div>
    </div>
  );
}

const TABS = [
  { id: "overview", label: "Overview", icon: "dashboard" },
  { id: "drugs", label: "Drug Classes", icon: "medication" },
  { id: "cohorts", label: "Patient Cohorts", icon: "groups" },
  { id: "trends", label: "Trends", icon: "trending_up" },
];

export default function AnalyticsDashboard({ onBack }) {
  const [tab, setTab] = useState("overview");
  const d = DATA;

  return (
    <div className="section">
      <div className="container">
        <button onClick={onBack} className="btn btn-s btn-sm" style={{ marginBottom: 24 }}>
          <span className="material-symbols-outlined" style={{ fontSize: 18 }}>arrow_back</span> Back to Risk Tool
        </button>

        <div style={{ marginBottom: 24 }}>
          <h2 className="sec-title" style={{ display: "flex", alignItems: "center", gap: 10 }}>
            <span className="material-symbols-outlined" style={{ fontSize: 32, color: "var(--accent)" }}>analytics</span>
            Population Analytics
          </h2>
          <p className="sec-sub" style={{ marginBottom: 0 }}>
            Insights from {d.overview.total_fills.toLocaleString()} prescription fills across {d.overview.total_patients.toLocaleString()} patients (CMS DE-SynPUF 2008–2010)
          </p>
        </div>

        <div className="an-tabs">
          {TABS.map((t) => (
            <button key={t.id} className={`an-tab${tab === t.id ? " active" : ""}`} onClick={() => setTab(t.id)}>
              <span className="material-symbols-outlined" style={{ fontSize: 18 }}>{t.icon}</span> {t.label}
            </button>
          ))}
        </div>

        {tab === "overview" && (
          <>
            <div className="an-stats-grid">
              <StatCard icon="description" value="1,473,595" label="Total Prescription Fills" color="#005c8f" />
              <StatCard icon="groups" value="67,085" label="Unique Patients" color="var(--accent)" />
              <StatCard icon="trending_down" value="76.2%" label="Overall Late Refill Rate" color="var(--coral)" sub="across all fills" />
              <StatCard icon="speed" value="0.525" label="Mean Risk Score" color="#8b5cf6" sub="median: 0.586" />
            </div>
            <SectionCard icon="stacked_bar_chart" title="Risk Tier Distribution" sub="Based on calibrated thresholds (LOW <0.30, MODERATE 0.30–0.55, HIGH ≥0.55)">
              <TierBar tier="HIGH" count={809536} pct={54.9} actualLate={88.2} color="var(--coral)" />
              <TierBar tier="MODERATE" count={397695} pct={27.0} actualLate={71.6} color="#d97706" />
              <TierBar tier="LOW" count={266364} pct={18.1} actualLate={46.3} color="#059669" />
            </SectionCard>
            <SectionCard icon="warning" title="High-Risk Patient Segment" sub={`${d.high_risk.count.toLocaleString()} patients (${d.high_risk.pct_of_total}% of cohort) whose most recent prediction was HIGH`}>
              <div className="an-stats-grid" style={{ gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))" }}>
                <StatCard icon="person_alert" value="47,272" label="High-Risk Patients" color="var(--coral)" />
                <StatCard icon="repeat" value="23.4" label="Mean Fills per Patient" color="#005c8f" />
                <StatCard icon="medication" value="11.2" label="Mean Drugs per Patient" color="#8b5cf6" />
                <StatCard icon="event_busy" value="80.2%" label="Mean Late Rate" color="var(--coral)" />
              </div>
            </SectionCard>
          </>
        )}

        {tab === "drugs" && (
          <>
            <SectionCard icon="category" title="Risk by Drug Class" sub="Named drug classes resolved via RxNorm API (85% of fills are unresolved NDC-5 codes)">
              {d.by_drug_class.map((dc) => (
                <HBar key={dc.name} label={dc.name} value={`${dc.pct_late}%`} pct={dc.pct_late} color={dc.pct_late >= 90 ? "var(--coral)" : dc.pct_late >= 88 ? "#e89c0d" : "var(--accent)"} ci={wilsonCI(dc.pct_late, dc.n_fills)} />
              ))}
              <div style={{ fontSize: 12, color: "#9ca3af", marginTop: 12, fontStyle: "italic" }}>
                Bile acid sequestrants show highest late rate (91.3%). All resolved classes are cardiovascular medications, consistent with a Medicare population.
              </div>
            </SectionCard>
            <SectionCard icon="medication" title="Top Named Drugs" sub="Individual drugs resolved to brand/generic names">
              <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(280px, 1fr))", gap: 10 }}>
                {d.by_drug.map((drug) => (
                  <div key={drug.name} style={{ display: "flex", alignItems: "center", gap: 12, padding: "10px 14px", background: "#f9fafb", borderRadius: 8, border: "1px solid #f3f4f6" }}>
                    <span className="material-symbols-outlined" style={{ fontSize: 20, color: drug.pct_late >= 89 ? "var(--coral)" : "#d97706" }}>pill</span>
                    <div style={{ flex: 1, minWidth: 0 }}>
                      <div style={{ fontSize: 13, fontWeight: 600, color: "var(--navy)", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}>{drug.name}</div>
                      <div style={{ fontSize: 11, color: "#9ca3af" }}>{drug.n_fills.toLocaleString()} fills</div>
                    </div>
                    <div style={{ fontSize: 15, fontWeight: 800, fontFamily: "'Nunito',sans-serif", color: drug.pct_late >= 89 ? "var(--coral)" : "#d97706" }}>{drug.pct_late}%</div>
                  </div>
                ))}
              </div>
            </SectionCard>
          </>
        )}

        {tab === "cohorts" && (
          <>
            <SectionCard icon="cake" title="Risk by Age Group" sub="Late rates are remarkably consistent across ages: behaviour dominates demographics">
              {d.by_age.map((a) => (
                <HBar key={a.group} label={`${a.group} yr`} value={`${a.pct_late}%`} pct={a.pct_late} maxPct={80} color="var(--navy)" ci={wilsonCI(a.pct_late, a.n_fills)} />
              ))}
            </SectionCard>
            <div className="an-cohort-pair">
              <SectionCard icon="wc" title="Risk by Sex" sub="No meaningful difference">
                {d.by_sex.map((s) => (
                  <HBar key={s.label} label={s.label} value={`${s.pct_late}%`} pct={s.pct_late} maxPct={80} color={s.label === "Female" ? "#8b5cf6" : "#0088b3"} ci={wilsonCI(s.pct_late, s.n_fills)} />
                ))}
              </SectionCard>
              <SectionCard icon="diversity_3" title="Risk by Ethnicity" sub="Flat across groups">
                {d.by_race.map((r) => (
                  <HBar key={r.label} label={r.label} value={`${r.pct_late}%`} pct={r.pct_late} maxPct={80} color="var(--accent)" ci={wilsonCI(r.pct_late, r.n_fills)} />
                ))}
              </SectionCard>
            </div>
            <SectionCard icon="medical_information" title="Risk by Number of Chronic Conditions" sub="U-shaped: patients with 0 or 11 conditions have highest late rates">
              {d.by_chronic.map((c) => (
                <HBar key={c.n} label={`${c.n} conditions`} value={`${c.pct_late}%`} pct={c.pct_late} maxPct={82} color={c.n === 0 || c.n >= 10 ? "var(--coral)" : c.pct_late > 76 ? "#d97706" : "var(--accent)"} sub={`${c.n_patients.toLocaleString()} pts`} />
              ))}
              <div style={{ fontSize: 12, color: "#9ca3af", marginTop: 12, fontStyle: "italic" }}>
                Patients with zero recorded conditions (77.2% late) may have undiagnosed or under-coded illness. Those with 11 conditions (80.1% late) face extreme complexity managing multiple medications.
              </div>
            </SectionCard>
          </>
        )}

        {tab === "trends" && (
          <>
            <SectionCard icon="timeline" title="Quarterly Trends" sub="Late refill rate and high-risk proportion over time">
              <div style={{ overflowX: "auto" }}>
                <table className="an-table">
                  <thead>
                    <tr>
                      <th>Quarter</th>
                      <th style={{ textAlign: "right" }}>Fills</th>
                      <th style={{ textAlign: "right" }}>Late Rate</th>
                      <th>Trend</th>
                      <th style={{ textAlign: "right" }}>% High-Risk</th>
                      <th>Trend</th>
                    </tr>
                  </thead>
                  <tbody>
                    {d.by_quarter.map((q, i) => {
                      const prevLate = i > 0 ? d.by_quarter[i - 1].pct_late : q.pct_late;
                      const lateDelta = (q.pct_late - prevLate).toFixed(1);
                      const prevHigh = i > 0 ? d.by_quarter[i - 1].pct_high : q.pct_high;
                      const highDelta = (q.pct_high - prevHigh).toFixed(1);
                      return (
                        <tr key={q.label}>
                          <td style={{ fontWeight: 600 }}>{q.label}</td>
                          <td style={{ textAlign: "right", fontFamily: "'JetBrains Mono',monospace", fontSize: 13 }}>{q.n_fills.toLocaleString()}</td>
                          <td style={{ textAlign: "right", fontWeight: 700, color: q.pct_late >= 80 ? "var(--coral)" : q.pct_late >= 70 ? "#d97706" : "#059669" }}>{q.pct_late}%</td>
                          <td>
                            <div style={{ width: 100, height: 12, background: "#f3f4f6", borderRadius: 3, overflow: "hidden", display: "inline-block", verticalAlign: "middle", marginRight: 6 }}>
                              <div style={{ width: `${q.pct_late}%`, height: "100%", background: q.pct_late >= 80 ? "var(--coral)" : q.pct_late >= 70 ? "#d97706" : "#059669", borderRadius: 3 }} />
                            </div>
                            {i > 0 && <span style={{ fontSize: 11, color: lateDelta <= 0 ? "#059669" : "var(--coral)" }}>{lateDelta > 0 ? "+" : ""}{lateDelta}</span>}
                          </td>
                          <td style={{ textAlign: "right", fontWeight: 600 }}>{q.pct_high}%</td>
                          <td>
                            {i > 0 && <span style={{ fontSize: 11, color: highDelta <= 0 ? "#059669" : "var(--coral)" }}>{highDelta > 0 ? "+" : ""}{highDelta}</span>}
                          </td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>
              <div style={{ fontSize: 12, color: "#9ca3af", marginTop: 12, fontStyle: "italic" }}>
                The declining trend reflects 2010 data truncation (fewer observable next fills), not genuine improvement. Within 2008 to 2009, Q1 shows highest late rates, consistent with post-holiday medication lapses.
              </div>
            </SectionCard>
            <SectionCard icon="lightbulb" title="Key Insight" sub="What drives the risk, and what doesn't">
              <div className="an-cohort-pair">
                <div style={{ background: "#fef2f2", border: "1px solid #fecaca", borderRadius: 8, padding: 16 }}>
                  <div style={{ fontSize: 14, fontWeight: 700, color: "var(--coral)", marginBottom: 6, display: "flex", alignItems: "center", gap: 6 }}>
                    <span className="material-symbols-outlined" style={{ fontSize: 18 }}>priority_high</span> What drives late refills
                  </div>
                  <ul style={{ fontSize: 13, color: "#4b5563", lineHeight: 1.7, paddingLeft: 18, margin: 0 }}>
                    <li>Irregular past refill patterns (35% of model signal)</li>
                    <li>Short supply durations (30-day vs 90-day)</li>
                    <li>Few prior fills (new prescriptions)</li>
                    <li>History of previous late refills</li>
                  </ul>
                </div>
                <div style={{ background: "#f0fdf4", border: "1px solid #bbf7d0", borderRadius: 8, padding: 16 }}>
                  <div style={{ fontSize: 14, fontWeight: 700, color: "#059669", marginBottom: 6, display: "flex", alignItems: "center", gap: 6 }}>
                    <span className="material-symbols-outlined" style={{ fontSize: 18 }}>check_circle</span> What doesn't matter (much)
                  </div>
                  <ul style={{ fontSize: 13, color: "#4b5563", lineHeight: 1.7, paddingLeft: 18, margin: 0 }}>
                    <li>Age: nearly identical rates across all groups</li>
                    <li>Sex: 76.1% vs 76.3% (no difference)</li>
                    <li>Ethnicity: 75.8% to 76.3% (flat)</li>
                    <li>Number of chronic conditions (weak U-curve)</li>
                  </ul>
                </div>
              </div>
            </SectionCard>
          </>
        )}

        <div style={{ background: "#fff", borderRadius: "var(--card)", boxShadow: "var(--shadow)", padding: "16px 20px", display: "flex", alignItems: "flex-start", gap: 12, marginTop: 24 }}>
          <span className="material-symbols-outlined" style={{ fontSize: 20, color: "var(--accent)", flexShrink: 0, marginTop: 2 }}>info</span>
          <div style={{ fontSize: 12, color: "#6b7280", lineHeight: 1.6 }}>
            <strong style={{ color: "var(--navy)" }}>Synthetic data.</strong> All figures are from CMS DE-SynPUF (2008 to 2010), a fully synthetic dataset with deliberately altered correlations. Demographics appear flat because the synthesis process coarsened multivariate relationships. Real dispensing data would likely show meaningful variation by geography, socioeconomic status, and condition type.
          </div>
        </div>
      </div>
    </div>
  );
}
